---
title: "pubchem-sections"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{pubchem-sections}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(webchem)
```

## Names and Identifiers

PubChem pages contain various identifiers that can be retrieved using `webchem`. For example, to get the InChI of a compound:

```{r}
pc_sect(id = 1983, section = "inchi")
```

Here are some example section names that can be retrieved using `webchem`:

```{r, echo = FALSE}
pugview <- tibble::tribble(
  ~Section, ~Parser,
  "InChI", "table",
  "Molecular Formula", "table",
  "CAS", "table",
  "MeSH Entry Terms", "table",
  "Depositor-Supplied Synonyms", "table"
)

knitr::kable(pugview)
```

## Chemical and Physical Properties

Here are section names that have been tested to work with `webchem`:

```{r, echo = FALSE}
pugview <- tibble::tribble(
  ~Section, ~Parser,
  "Molecular Weight", "table",
  "XLogP3", "table",
  "Hydrogen Bond Donor Count", "table",
  "Hydrogen Bond Acceptor Count", "table",
  "Rotatable Bond Count", "table",
  "Exact Mass", "table",
  "Monoisotopic Mass", "table",
  "Topological Polar Surface Area", "table",
  "Heavy Atom Count", "table",
  "Formal Charge", "table",
  "Complexity", "table",
  "Isotope Atom Count", "table",
  "Defined Atom Stereocenter Count", "table",
  "Undefined Atom Stereocenter Count", "table",
  "Defined Bond Stereocenter Count", "table",
  "Undefined Bond Stereocenter Count", "table",
  "Covalently-Bonded Unit Count", "table",
  "Compound Is Canonicalized", "table",
  "Physical Description", "table",
  "Odor", "table",
  "Taste", "table",
  "Boiling Point", "table",
  "Melting Point", "table",
  "Solubility", "table",
  "Density", "table",
  "Vapor Density", "table",
  "Vapor Pressure", "table",
  "LogP", "table",
  "Autoignition Temperature", "table",
  "pH", "table",
  "Dissociation Constants", "table",
  "Collision Cross Section", "table"
)

knitr::kable(pugview)
```
