# based on https://docs.ropensci.org/rotemplate/

on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master

name: check-pkgdown

jobs:
  check_pkgdown:
    runs-on: ubuntu-latest
    steps:
      - uses: ropensci-org/rotemplate@main