on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master

name: check-pkgdown

jobs:
    check_pkgdown:
      runs-on: ubuntu-22.04

      env:
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

      steps:
        - uses: actions/checkout@v4
        - uses: r-lib/actions/setup-r@v2
          with:
            r-version: 'release'
        - uses: r-lib/actions/setup-r-dependencies@v2
          with:
            extra-packages: any::devtools, any::pkgdown

        - name: Install dependencies
          run: devtools::install_github("https://github.com/ropensci-org/rotemplate")
          shell: Rscript {0}

        - name: Check pkgdown
          run: pkgdown::check_pkgdown()
          shell: Rscript {0}
